const colors = {
  light: {
    text: '#1A1A1A',
    tint: '#1A1A1A',
    background: '#F8F5F0',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    primary: '#1A1A1A',
    primaryForeground: '#FFFFFF',
    secondary: '#EEEBE6',
    secondaryForeground: '#1A1A1A',
    muted: '#EEEBE6',
    mutedForeground: '#888888',
    accent: '#E84855',
    accentForeground: '#FFFFFF',
    destructive: '#E84855',
    destructiveForeground: '#FFFFFF',
    border: '#E8E4DF',
    input: '#E8E4DF',
  },
  dark: {
    text: '#1A1A1A',
    tint: '#1A1A1A',
    background: '#F8F5F0',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    primary: '#1A1A1A',
    primaryForeground: '#FFFFFF',
    secondary: '#EEEBE6',
    secondaryForeground: '#1A1A1A',
    muted: '#EEEBE6',
    mutedForeground: '#888888',
    accent: '#E84855',
    accentForeground: '#FFFFFF',
    destructive: '#E84855',
    destructiveForeground: '#FFFFFF',
    border: '#E8E4DF',
    input: '#E8E4DF',
  },
  radius: 12,
};

export default colors;

export const GAME_COLORS = {
  arrowPrimary: '#1A1A1A',
  arrowAccent: '#E84855',
  background: '#F8F5F0',
  surface: '#FFFFFF',
  gridDot: '#D6D1CA',
} as const;
